/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RelCidades.java
 *
 * Created on 17/10/2011, 22:08:51
 */
package visao;

import controle.EstadoControle;
import dao.Conexao;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import modelo.Estado;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Yuri
 */
public class RelCidades extends javax.swing.JDialog {

  private List<Estado> lista = new ArrayList<Estado>();
    private Estado est;
    private EstadoControle controle;
 
   
    /** Creates new form RelCidades */
    public RelCidades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controle = EstadoControle.getInstance();
        montaCombo();
        
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox();
        btGera = new javax.swing.JButton();
        btCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Estado");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btGera.setText("Gera Relatório");
        btGera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGeraActionPerformed(evt);
            }
        });

        btCancela.setText("Cancela");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btGera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGera)
                    .addComponent(btCancela))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGeraActionPerformed
        try {
            Estado esta = lista.get(comboEstado.getSelectedIndex());
            Long i = esta.getId();
            Map parametros = new HashMap();
            parametros.put("FILTRO_CIDADE", i);
            URL arquivo = getClass().getResource("/relatorios/RelCidades.jasper"); 
            JasperReport relatorio = (JasperReport) JRLoader.loadObject(arquivo);
            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, Conexao.getConnection());
                  
            JasperViewer visualizador = new JasperViewer(impressao,false);
            visualizador.setTitle("Relatório de Cidades");
            visualizador.setAlwaysOnTop(true);
            visualizador.setVisible(true);
            this.dispose();
            
           
            
            
        } catch (Exception e) {
            System.out.println("Erro "+ e);
        }
    }//GEN-LAST:event_btGeraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                final RelCidades dialog = new RelCidades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    
                    public void windowClosing(java.awt.event.WindowEvent e) {
                       dialog.dispose();
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancela;
    private javax.swing.JButton btGera;
    private javax.swing.JComboBox comboEstado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void montaCombo() {
        comboEstado.removeAllItems();
        lista = controle.listaTodos();
        for (Estado est : lista) {
            comboEstado.addItem(est.getNome());
        }
    }
}
