/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 05/10/2011, 16:26:54
 */
package visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Lucas
 */
public class TelaPrincipal extends javax.swing.JFrame implements ActionListener {

    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        initComponents();
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage("icones/SGCLOGO.png"));
        setExtendedState(MAXIMIZED_BOTH);
        
    }

    public void actionPerformed(java.awt.event.ActionEvent e) {
        if (e.getSource() == menuProdutos) {
            ProdutoCad prodcad = new ProdutoCad(this, true);
            prodcad.setLocationRelativeTo(null);
            prodcad.setVisible(true);
        } else if (e.getSource() == menucidades) {
            CidadeCad cidcad = new CidadeCad(this, true);
            cidcad.setLocationRelativeTo(null);
            cidcad.setVisible(true);
        } else if (e.getSource() == menuestados) {
            EstadoCad estcad = new EstadoCad(this, true);
            estcad.setLocationRelativeTo(null);
            estcad.setVisible(true);
        } else if (e.getSource() == menurelcidades) {
            RelCidades relcid = new RelCidades(this, true);
            relcid.setLocationRelativeTo(null);
            relcid.setVisible(true);
        } else if (e.getSource() == menuvendas) {
            VendasCad vc = new VendasCad(this, true);
            vc.setLocationRelativeTo(null);
            vc.setVisible(true);
        } else if (e.getSource() == menugrupo) {
            GrupoCad gp = new GrupoCad(this, true);
            gp.setLocationRelativeTo(null);
            gp.setVisible(true);
        } else if (e.getSource() == menurelvendas) {
            VendasCon vcc = new VendasCon(this, true);
            vcc.setLocationRelativeTo(null);
            vcc.setVisible(true);
        } else if (e.getSource() == menupessoas) {
            PessoaCad pescad = new PessoaCad(this, true);
            pescad.setLocationRelativeTo(null);
            pescad.setVisible(true);
        } else if (e.getSource() == menuusuario) {
            UsuarioCad uscad = new UsuarioCad(this, true);
            uscad.setLocationRelativeTo(null);
            uscad.setVisible(true);

        } else if (e.getSource() == menuempresa) {
            EmpresaCad emp = new EmpresaCad(this, true);
            emp.setLocationRelativeTo(null);
            emp.setVisible(true);

        }   else if (e.getSource() == menucompras) {
            ComprasCad cp = new ComprasCad(this, true);
            cp.setLocationRelativeTo(null);
            cp.setVisible(true);

        }
    }

            /** This method is called from within the constructor to
             * initialize the form.
             * WARNING: Do NOT modify this code. The content of this method is
             * always regenerated by the Form Editor.
             */
            @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painellgo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuGestao = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        menuProdutos = new javax.swing.JMenuItem();
        menuProdutos.addActionListener(this);
        menugrupo = new javax.swing.JMenuItem();
        menugrupo.addActionListener(this);
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        menucidades = new javax.swing.JMenuItem();
        menucidades.addActionListener(this);
        menuestados = new javax.swing.JMenuItem();
        menuestados.addActionListener(this);
        menupessoas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuusuario = new javax.swing.JMenuItem();
        menuusuario.addActionListener(this);
        jMenu2 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        menuvendas = new javax.swing.JMenuItem();
        menuvendas.addActionListener(this);
        jmenu233 = new javax.swing.JMenu();
        menucompras = new javax.swing.JMenuItem();
        menucompras.addActionListener(this);
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menurelcidades = new javax.swing.JMenuItem();
        menurelcidades.addActionListener(this);
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuPessoas = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menurelvendas = new javax.swing.JMenuItem();
        menurelvendas.addActionListener(this);
        menurelcompras = new javax.swing.JMenuItem();
        menurelcompras.addActionListener(this);
        jMenu4 = new javax.swing.JMenu();
        menuempresa = new javax.swing.JMenuItem();
        menuempresa.addActionListener(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGC - SISTEMA DE GERENCIAMENTO COMERCIAL");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        painellgo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("SGC - Sistema de Gerenciamento Comercial");

        javax.swing.GroupLayout painellgoLayout = new javax.swing.GroupLayout(painellgo);
        painellgo.setLayout(painellgoLayout);
        painellgoLayout.setHorizontalGroup(
            painellgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painellgoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        painellgoLayout.setVerticalGroup(
            painellgoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painellgoLayout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(74, 74, 74))
        );

        menuGestao.setText("Gestão");

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/produto.png"))); // NOI18N
        jMenu7.setText("Produtos");

        menuProdutos.setText("Gestão de Produtos");
        menuProdutos.setToolTipText("Cadastra produtos diversos no banco de dados");
        jMenu7.add(menuProdutos);

        menugrupo.setText("Grupos de Produtos");
        jMenu7.add(menugrupo);

        menuGestao.add(jMenu7);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cliadd.png"))); // NOI18N
        jMenu5.setText("Pessoas");

        jMenu8.setText("Localidade");

        menucidades.setText("Cidades");
        jMenu8.add(menucidades);

        menuestados.setText("Estados");
        jMenu8.add(menuestados);

        jMenu5.add(jMenu8);

        menupessoas.setText("Pessoas");
        menupessoas.addActionListener(this);
        jMenu5.add(menupessoas);
        jMenu5.add(jSeparator1);

        menuusuario.setText("Usuários do Sistema");
        jMenu5.add(menuusuario);

        menuGestao.add(jMenu5);

        barraMenu.add(menuGestao);

        jMenu2.setText("Movimentos");

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit.png"))); // NOI18N
        jMenu9.setText("Vendas");

        menuvendas.setText("Lançamento de Vendas");
        jMenu9.add(menuvendas);

        jMenu2.add(jMenu9);

        jmenu233.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/recebe.png"))); // NOI18N
        jmenu233.setText("Produtos");

        menucompras.setText("Entrada");
        jmenu233.add(menucompras);

        jMenu2.add(jmenu233);
        jMenu2.add(jSeparator3);

        barraMenu.add(jMenu2);

        jMenu3.setText("Relatórios");

        jMenu1.setText("Cadastrais");

        menurelcidades.setText("Cidades");
        jMenu1.add(menurelcidades);

        jMenuItem1.setText("Estados");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Usuarios");
        jMenu1.add(jMenuItem2);

        menuPessoas.setText("Pessoas");
        jMenu1.add(menuPessoas);

        jMenuItem4.setText("Produtos");
        jMenu1.add(jMenuItem4);

        jMenu3.add(jMenu1);

        jMenu6.setText("Gerenciais");

        menurelvendas.setText("Vendas");
        jMenu6.add(menurelvendas);

        menurelcompras.setText("Compras");
        jMenu6.add(menurelcompras);

        jMenu3.add(jMenu6);

        barraMenu.add(jMenu3);

        jMenu4.setText("Ferramentas");

        menuempresa.setText("Configurar Empresa");
        jMenu4.add(menuempresa);

        barraMenu.add(jMenu4);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painellgo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painellgo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
}//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu jmenu233;
    private javax.swing.JMenu menuGestao;
    private javax.swing.JMenuItem menuPessoas;
    private javax.swing.JMenuItem menuProdutos;
    private javax.swing.JMenuItem menucidades;
    private javax.swing.JMenuItem menucompras;
    private javax.swing.JMenuItem menuempresa;
    private javax.swing.JMenuItem menuestados;
    private javax.swing.JMenuItem menugrupo;
    private javax.swing.JMenuItem menupessoas;
    private javax.swing.JMenuItem menurelcidades;
    private javax.swing.JMenuItem menurelcompras;
    private javax.swing.JMenuItem menurelvendas;
    private javax.swing.JMenuItem menuusuario;
    private javax.swing.JMenuItem menuvendas;
    private javax.swing.JPanel painellgo;
    // End of variables declaration//GEN-END:variables
}
